### ISSUE TITLE
Support for dotNetCore (AspNet RC2)

### ISSUE THREAD

**Issue by betimd** [gingemonster/dotnet-opencage-geocode#1]
Upgraded my project to AspNet Core RC2 and lib didn't work.

**Comment by gingemonster** [comment]
Can you give me any more info, the error details for example

**Comment by betimd** [comment]
Just make new project using dotnetcore or aspnet core app, reference your library and you'll get errors.
Lib needs support for donetcore.

**Comment by betimd** [comment]
Now it could be great to go straight to .Net Core support / Asp.Net Core

**Comment by gingemonster** [comment]
Hi

Will take a look and see if I can fix asap but lots on right now

**Comment by gingemonster** [comment]
The latest release (v 1.2) is now a .Net standard library so will work in .Net core
