### ISSUE TITLE
No house number in reverse geocode

### ISSUE THREAD

**Issue by timonmasberg** [gingemonster/dotnet-opencage-geocode#11]
Currently the geocoder respond does not include a house number which can be found in the json "components"->"house_number"

**Comment by timonmasberg** [comment]
I just found that there is a cictionary where you can get these values, but you might want to implement "house_number" when you already have "road" into the component class. Consider this as a feature request. Thanks

**Comment by gingemonster** [comment]
Fancy doing the change and submitting a pull request?

Brian Norman
CTO
T: +44 (0)845 6429 880
E: brian@earthware.co.uk<mailto:brian@earthware.co.uk>
W: www.earthware.co.uk<http://www.earthware.co.uk/>


[Earthware_Logo_Lock_Up_Small]<http://www.earthware.co.uk/>

Join our conversation: Blog<http://www.earthware.co.uk/blog>   Twitter<https://twitter.com/earthware>   LinkedIn<https://www.linkedin.com/company-beta/387715/>

This email (including attachments) is confidential and intended only for stated addressee(s). This email is sent on behalf of earthware Limited<http://www.earthware.co.uk/>, a company registered in England and Wales under registered number 06047986. Earthware’s registered address is 2 Church Barn, Caldecote Road, Newnham, Hertfordshire, SG7 5LA.
