### ISSUE TITLE
is this project being maintained?

### ISSUE THREAD

**Issue by freyfogle** [gingemonster/dotnet-opencage-geocode#3]
Hi,

I'm Ed, one of the makers of the OpenCage Geocoder. This code works, but has not kept up with all the improvements we've made to the service in the last years. I would love to see it modernized. I'm not a .NET programmer. I'm happy to pay anyone who wants to work with us to give it a refresh. Please get in touch if interested.

**Comment by gingemonster** [comment]
Hi Ed

Let me know a good time to call and perhaps you can talk me through the new features then I can get someone to implement them

Thanks
Brian@earthware.co.uk

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by freyfogle** [comment]
Hi Brian,  

thanks for the fast follow up  - and for writing the code in the first place. Much appreciated.

Basically there are three things needed:

1. support for [the various optional parameters ](https://geocoder.opencagedata.com/api#forward-opt)

2. deal with [the rate limiting](https://geocoder.opencagedata.com/api#rate-limiting) in a good way. Two cases:
a. user goes over the free trial limit of 2,500 per day should get a meaningful error message 
b. user is a paid customer and thus doesn't have rate limiting (there is no `rate` section in the response). The code should keep working. 

3. improve the README to include a pointer to [the best practices](https://geocoder.opencagedata.com/api#bestpractices) and possibly more examples 

That's it. It is not some major change. My guess is a few hours of work. I can gladly help on part 3.

Happy to pay you a reasonable day rate to do this work, either in money or in free geocoding. Happy of course to also give you a paid account for testing. Once it's ready we'll do a post on our blog and of course give you full credit for your efforts (see [recent post about our iOS SDK](https://blog.opencagedata.com/2017/12/04/new-ios-sdk.html))

Please let me know. If useful of course happy to do a call or to move the discussion to email. 
You can reach me at edf @ opencagedata.com

thanks again, it is appreciated.
Ed

**Comment by gingemonster** [comment]
Hi Ed

A new version has been released that includes many improvements:

- Complete support for optional parameters, etc where it doesn't make sense like jsonp and pretty
- Better error messages to handle rate limiting
- Improved readme with pointers to best practices and more complete examples
- Complete support for the newer response data annotations
- Moved to .Net Standard meaning the library can now be used in .Net projects on practically every platform

If you wish to credit my please can you say "Brian Norman, earthware.co.uk" thanks

Brian

**Comment by freyfogle** [comment]
Hi Brian, this is fantastic. Great work. Will do a blog post about it on Monday.
