### ISSUE TITLE
ResponseObjects in global namespace

### ISSUE THREAD

**Issue by BamButz** [gingemonster/dotnet-opencage-geocode#9]
Hello,

first of all thanks for this great work.

Now to my problem, as far as I can see some objects are in the global namespace that collide with other classes of the same name.

Is it possible to move them into a project specific namespace or would it cause problems that are not known to me?

e.g.
[dotnet-opencage-geocode/OpenCage.Geocode/ResponseObjects/License.cs](https://github.com/gingemonster/dotnet-opencage-geocode/blob/14e9eb8fe98a24671c15ca7ee957a7807c1bcb83/OpenCage.Geocode/ResponseObjects/License.cs)
[dotnet-opencage-geocode/OpenCage.Geocode/ResponseObjects/Annotations.cs](https://github.com/gingemonster/dotnet-opencage-geocode/blob/14e9eb8fe98a24671c15ca7ee957a7807c1bcb83/OpenCage.Geocode/ResponseObjects/Annotations.cs)

Bounds is already in a proper namespace so I think it shouldn't be a problem?
[dotnet-opencage-geocode/OpenCage.Geocode/ResponseObjects/Bounds.cs](https://github.com/gingemonster/dotnet-opencage-geocode/blob/14e9eb8fe98a24671c15ca7ee957a7807c1bcb83/OpenCage.Geocode/ResponseObjects/Bounds.cs)

Best wishes

**Comment by gingemonster** [comment]
Hi

To be honest I’m not 100% sure if that would cause and issue or not. Have you tried doing it locally, worth and try and then test it and submit a pull request and I can review

Brian Norman
CTO
T: +44 (0)845 6429 880
E: brian@earthware.co.uk<mailto:brian@earthware.co.uk>
W: www.earthware.co.uk<http://www.earthware.co.uk/>


[Earthware_Logo_Lock_Up_Small]<http://www.earthware.co.uk/>

Join our conversation: Blog<http://www.earthware.co.uk/blog>   Twitter<https://twitter.com/earthware>   LinkedIn<https://www.linkedin.com/company-beta/387715/>

This email (including attachments) is confidential and intended only for stated addressee(s). This email is sent on behalf of earthware Limited<http://www.earthware.co.uk/>, a company registered in England and Wales under registered number 06047986. Earthware’s registered address is 2 Church Barn, Caldecote Road, Newnham, Hertfordshire, SG7 5LA.
